# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
        - id: black

-   repo: local
    hooks:
        - id: coverage
          name: "Run tests and check code coverage"
          types: [file, python]
          entry: python coverage_pre_commit_hook.py
          language: "python"
          files: ^testing/ ^src/
          additional_dependencies: ['beautifulsoup4==4.9.1', 'typer==0.3.2', 'click==7.1.2']
          args: [--goal-percentage-total=101, --goal-percentage-individual=80]