# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
        - id: black

-   repo: local
    hooks:
        - id: coverage
          name: "Run code coverage"
          types: [file, python]
          entry: coverage run --source=./ -m unittest testing.test
          language: "python"
          always_run: true

        - id: coverage-report
          name: "Create html coverage report"
          types: [file, python]
          entry: coverage html
          language: "python"
          always_run: true

